version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    tty: true
    networks:
      - anicheck
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    tty: true
    networks:
      - anicheck
networks:
  anicheck:
    external: true